# Generated by Django 3.0.1 on 2019-12-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First Player To Move'), ('S', 'Second Plyer To Move'), ('W', 'First Player Won'), ('L', 'Second Player Won'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
